### ISSUE TITLE
create_table(:configs) undefined method `code' for #<Exchange:0x00005555d66615d0>

### ISSUE THREAD

**Issue by DT021** [a-kushnir/x-stocks#4]
rake db:migrate
== 20200706000000 CreateTables: migrating =====================================
-- create_table(:exchanges)
   -> 0.0089s
-- create_table(:stocks)
   -> 0.0171s
-- create_table(:tags)
   -> 0.0140s
-- create_table(:positions)
   -> 0.0203s
-- create_table(:configs)
   -> 0.0113s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `code' for #<Exchange:0x00005555d66615d0>

**Comment by DT021** [comment]
Any help would be appreciated

**Comment by a-kushnir** [comment]
Migrations fixed, please try again using the latest version of code.
Default credentials: admin@admin.com/admin!

This software requires free keys from https://finnhub.io/ and https://iexcloud.io/ which can be provided using config vars with names FINNHUB_KEY, FINNHUB_KEY_2, etc. and the same with IEXAPIS_KEY
I'll update readme file soon.

Let me know if you have any questions
